### ISSUE TITLE
Make an explicit statement whether generated code is under GPL3 or not

### ISSUE THREAD

**Issue by tv42** [opennota/re2dfa#5]
The code generation logic includes GPL3'd string literals as part of the generated source, meaning that without a further statement the result is a derived work, and thus must be GPL3 also. Is this intended? Hopefully not..

You still have just one committer, you can change the licensing. Please add an exception that makes the generated code usable with any license.

Semi-related, from GCC:
https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html
http://www.gnu.org/licenses/gcc-exception-3.1-faq.en.html

**Comment by opennota** [comment]
I'll add a note to the README that the generated source isn't GPL and can be used freely. Hopefully this will be enough.
