### ISSUE TITLE
Replace string?

### ISSUE THREAD

**Issue by Oxygend** [opennota/re2dfa#7]
Not sure If I am at the right place but what I am doing is:
```Go
r := regexp.MustCompile(`([#@])|[\p{P}\p{S}\d]`)
r.ReplaceAllString(text, "$1")
```

Will this work with re2dfa? And if so, how to implement string replacement?

**Comment by opennota** [comment]
re2dfa only does the matching part. Replacement is a whole new kettle of fish.
